# Generated by Django 3.2.4 on 2021-07-01 06:29

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=100)),
                ('Mulai', models.DateTimeField()),
                ('Selesai', models.DateTimeField(blank=True)),
                ('Lokasi', models.TextField(blank=True)),
                ('Link', models.URLField(blank=True)),
                ('Keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembicara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('Pekerjaan', models.CharField(max_length=100)),
                ('Deskripsi_singkat', models.TextField(blank=True)),
                ('Foto', models.ImageField(upload_to='web/')),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Facebook', models.URLField(blank=True)),
                ('Twitter', models.URLField(blank=True)),
                ('Linkedin', models.URLField(blank=True)),
                ('Instagram', models.URLField(blank=True)),
                ('Keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListPembicara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.event')),
                ('Pembicara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.pembicara')),
            ],
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=150)),
                ('Tanggal', models.DateField(null=True)),
                ('Isi', tinymce.models.HTMLField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
