# Generated by Django 3.2.4 on 2021-07-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Acara', 'verbose_name_plural': 'Acara'},
        ),
        migrations.AlterModelOptions(
            name='listpembicara',
            options={'verbose_name': 'Daftar Pembicara', 'verbose_name_plural': 'Daftar Pembicara'},
        ),
        migrations.AlterModelOptions(
            name='pembicara',
            options={'verbose_name': 'Pembicara', 'verbose_name_plural': 'Pembicara'},
        ),
        migrations.AddField(
            model_name='artikel',
            name='Slug',
            field=models.SlugField(default='', editable=False, max_length=140),
        ),
        migrations.AddField(
            model_name='event',
            name='Slug',
            field=models.SlugField(default='', editable=False, max_length=140),
        ),
        migrations.AddField(
            model_name='pembicara',
            name='Slug',
            field=models.SlugField(default='', editable=False, max_length=140),
        ),
    ]
