# Generated by Django 3.2.4 on 2021-07-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210708_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Pembicara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.pembicara'),
        ),
    ]
