# Generated by Django 3.2.4 on 2021-07-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_event_pembicara'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembicara',
            name='Perusahaan',
            field=models.CharField(default='Google', max_length=100),
            preserve_default=False,
        ),
    ]
