# Generated by Django 3.2.4 on 2021-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_pembicara_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembicara',
            name='keynote',
            field=models.BooleanField(default=True),
        ),
    ]
