# Generated by Django 3.2.4 on 2021-07-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_pembicara_keynote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='web/logosponsor')),
                ('kategori', models.CharField(choices=[('0', 'University Sponsors'), ('1', 'Corporate Sponsors'), ('2', 'Media Sponsors')], default=0, max_length=1)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
    ]
