# Generated by Django 3.2.4 on 2021-08-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(blank=True, max_length=150)),
                ('foto', models.ImageField(blank=True, upload_to='web/teams/')),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
    ]
