# Generated by Django 3.2.4 on 2021-08-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AddField(
            model_name='team',
            name='no_urut',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
