# Generated by Django 3.2.4 on 2021-08-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210806_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='panggilan',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
