# Generated by Django 3.2.4 on 2021-08-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_team_scientific_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembicara',
            name='panggilan',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
